substitutions:
  devicename: ble-tracker
  formated_name: BLE Tracker
  ip_address: 10.0.2.58

<<: !include common/esphome/nodemcu_32s_esp_idf.yaml

<<: !include common/common_esp_idf.yaml
 
sensor:
  # Reports how long the device has been powered (in hours) since last reboot
  - platform: uptime
    name: ${formated_name} Uptime
    update_interval: 60s
    filters:
      - lambda: return x / 3600;
    unit_of_measurement: "h"
  - platform: wifi_signal
    name: "${formated_name} Wifi Signal"
    update_interval: 60s

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
