substitutions:
  devicename: shelly-pool-ligth-stairs
  formated_name: Shelly Pool Light Stairs
  # Name for the relays
  channel_1: Stairs
  max_power: "2000.0" # watt
  max_temp: "83.0" # °C

  comment: |-
    Location in the pool filter and controls the rgb lights on the back of the pool

<<: !include common/esphome/esp01_1m.yaml

<<: !include common/common.yaml

sensor:
  # Reports how long the device has been powered (in hours) since last reboot
  - platform: uptime
    name: ${formated_name} Uptime
    update_interval: 60s
    filters:
      - lambda: return x / 3600;
    unit_of_measurement: "h"
  - platform: wifi_signal
    name: "${formated_name} Wifi Signal"
    update_interval: 60s
  - platform: adc
    pin: A0
    name: "${formated_name} Power"
    update_interval: 1s

light:
  - platform: rgb
    name: "Pool Lights ${channel_1}"
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    # white: pwm_w
    effects:
      - random:
      - strobe:
      - flicker:

output:
  - platform: esp8266_pwm
    pin: GPIO12
    frequency: 1000 Hz
    id: pwm_r

  - platform: esp8266_pwm
    pin: GPIO15
    frequency: 1000 Hz
    id: pwm_g

  - platform: esp8266_pwm
    pin: GPIO14
    frequency: 1000 Hz
    id: pwm_b

  # - platform: esp8266_pwm
  #   pin: GPIO4
  #   frequency: 1000 Hz
  #   id: pwm_w
