substitutions:
  devicename: shelly-masterbedroom
  formated_name: Shelly Master Bedroom
  # Name for the relays
  channel_1: Ceiling Light

  comment: |-
    Placed in the master bedroom and control main lights

<<: !include common/esphome/esp01_1m.yaml

<<: !include common/common.yaml

# Device Specific Config
output:
  - platform: gpio
    pin: GPIO4
    id: shelly_bedroom_relay

light:
  - platform: binary
    name: ${channel_1}
    output: shelly_bedroom_relay
    id: lightid

sensor:
  # Reports how long the device has been powered (in hours) since last reboot
  - platform: uptime
    name: ${formated_name} Uptime
    update_interval: 60s
    filters:
      - lambda: return x / 3600;
    unit_of_measurement: "h"
  - platform: wifi_signal
    name: "${formated_name} Wifi Signal"
    update_interval: 60s

switch:
  - platform: restart
    name: "Restart"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
      #mode: INPUT_PULLUP
      #inverted: True
    name: ${channel_1} Switch
    on_state:
      then:
        - light.toggle: lightid
    internal: true
    id: switchid
