substitutions:
  devicename: sonoff_heater
  formated_name: Sonoff Heater
  ip_address: 10.0.2.202

<<: !include common/esphome/esp01_1m.yaml

<<: !include common/common.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff Basic Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Sonoff Basic Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
    
text_sensor:
  - platform: homeassistant
    id: heater_status
    entity_id: climate.heater
    attribute: hvac_action