substitutions:
  led_gpio: GPIO13
  rel1_gpio: GPIO12
  rel2_gpio: GPIO5
  rel3_gpio: GPIO4
  rel4_gpio: GPIO15
  key1_gpio: GPIO0
  key2_gpio: GPIO9
  key3_gpio: GPIO10
  key4_gpio: GPIO14
  rx_gpio: GPIO3
  tx_gpio: GPIO1

  devicename: sonoff-irrigation-a
  formated_name: Sprinkler A
  ip_address: 10.0.2.103
  comment: |-
    Irrigation controller A.
    Backyard

    Location: Green Garden Backyard
    Device: Sonoff 4ch R3

  valve_switch_1_name: ${formated_name}1 - Terraza
  valve_switch_2_name: ${formated_name}2 - Jardinera Fondo
  valve_switch_3_name: ${formated_name}3 - Pasto Shine
  valve_switch_4_name: ${formated_name}4 - Pasto Shade

<<: !include common/esphome/esp01_1m_irrigation.yaml

<<: !include common/common.yaml

<<: !include packages/irrigation/base.yaml

sprinkler:
  - id: sprinkler_controller
    main_switch: ${formated_name} - Run Now All
    auto_advance_switch:
      name: ${formated_name} - Auto Enabled
      restore_mode: RESTORE_DEFAULT_ON
    standby_switch: ${formated_name} - Standby
    multiplier_number:
      name: "${formated_name} - Multiplier"
      initial_value: 1
      unit_of_measurement: times
      min_value: 0.1
      max_value: 5
    valves:
      - valve_switch: $valve_switch_1_name - Run
        valve_switch_id: relay1
        enable_switch:
          name: $valve_switch_1_name - Auto
          restore_mode: RESTORE_DEFAULT_ON
        run_duration_number:
          name: $valve_switch_1_name - Duration
          initial_value: 10
          unit_of_measurement: min
      - valve_switch: $valve_switch_2_name - Run
        valve_switch_id: relay2
        enable_switch:
          name: $valve_switch_2_name - Auto
          restore_mode: RESTORE_DEFAULT_ON
        run_duration_number:
          name: $valve_switch_2_name - Duration
          initial_value: 12
          unit_of_measurement: min
      - valve_switch: $valve_switch_3_name - Run
        valve_switch_id: relay3
        enable_switch:
          name: $valve_switch_3_name - Auto
          restore_mode: RESTORE_DEFAULT_ON
        run_duration_number:
          name: $valve_switch_3_name - Duration
          initial_value: 10
          unit_of_measurement: min
      - valve_switch: $valve_switch_4_name - Run
        valve_switch_id: relay4
        enable_switch:
          name: $valve_switch_4_name - Auto
          restore_mode: RESTORE_DEFAULT_ON
        run_duration_number:
          name: $valve_switch_4_name - Duration
          initial_value: 2
          unit_of_measurement: min

sensor:
  # Reports how long the device has been powered (in hours) since last reboot
  - platform: uptime
    name: ${formated_name} - Uptime
  - platform: wifi_signal
    name: "${formated_name} - Wifi Signal"

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/Santiago

  - platform: sntp
    id: sntp_time
    timezone: America/Santiago
    on_time_sync:
      then:
        - logger.log:
            level: INFO
            format:  "Time synchronized"
    on_time:
      # Every morning on weekdays
      - seconds: 0
        minutes: 30
        hours: 21
        then:
          - sprinkler.start_full_cycle: sprinkler_controller

# number:
#   - id: backyard_start_time
#     platform: template
#     name: "Backyard Start Time"
#     mode: box
#     lambda: 'return id(sntp_time);'

# number:
#   - platform: template
#     id: backyard_ctrlr_multiplier
#     name: "Backyard Sprinkler Controller Multiplier"
#     min_value: 0.1
#     max_value: 10.0
#     step: 0.1
#     lambda: "return id(backyard).multiplier();"
#     set_action:
#       - sprinkler.set_multiplier:
#           id: backyard
#           multiplier: !lambda 'return x;'

# text_sensor:
#   - platform: homeassistant
#     name: "Start Timer"
#     id: backyard_start_time_helper
#     entity_id: input_datetime.start_irrigation
#     on_value:
#       then:
#         - lambda: |-
#             ESP_LOGD("main", "Old stored value  %i", id(my_global_int_hour));
#             ESP_LOGD("main", "The helper time is  %s", x.c_str());
#             id(my_global_int_hour) = id(my_global_int_hour) + 1;

# globals:
#    - id: my_global_int_hour
#      type: int
#      restore_value: yes
#      initial_value: '19'
