substitutions:
  devicename: sonoff-heater
  formated_name: Sonoff Heater
  ip_address: 10.0.2.202

<<: !include common/esphome/esp01_1m.yaml

<<: !include common/common.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff Basic Button"
    internal: true
    on_press:
      - switch.toggle: relay

# logger:
#   level: VERBOSE

switch:
  - platform: gpio
    name: "Sonoff Basic Relay"
    internal: true
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
    
# text_sensor:
#   - platform: homeassistant
#     id: heater_status
#     entity_id: climate.heater
#     attribute: hvac_action

sensor:
  - platform: homeassistant
    name: "Living Room Temperature"
    id: living_room_temp
    entity_id: sensor.multisensor_6_air_temperature
    
  - platform: homeassistant
    id: family_room_temp
    name: "Family Room Temperature"
    entity_id: sensor.sensor_air_temperature_2
    
  - platform: homeassistant
    id: master_bedroom_temp
    name: "Master Bedroom Temperature"
    entity_id: sensor.4_in_1_sensor_air_temperature
    
  - platform: homeassistant
    id: kitchen_temp
    name: "Kitchen Temperature"
    entity_id: sensor.kitchen_temperature
    
  - platform: kalman_combinator
    id: read_temperature
    name: "Read Temperature"
    unit_of_measurement: 째C
    process_std_dev: 0.001
    sources:
      - source: living_room_temp
        error: 1.0
      - source: family_room_temp
        error: 1.0
      - source: master_bedroom_temp
        error: 1.0

climate:
  - platform: thermostat
    visual:
      min_temperature: 15 째C
      max_temperature: 24 째C
      temperature_step: 0.5 째C
    name: "Heating"
    sensor: read_temperature
    default_target_temperature_low: 17.0
    min_heating_off_time: 100s
    min_heating_run_time: 100s
    min_idle_time: 30s
    heat_action:
      - switch.turn_on: relay
    idle_action:
      - switch.turn_off: relay
    # preset:
    #   # Standard Preset
    #   - name: sleep
    #     mode: HEAT
    #     default_target_temperature_low: 15.0
    #   - name: morning
    #     mode: HEAT
    #     default_target_temperature_low: 18.0