substitutions:
  led_gpio: GPIO13
  rel1_gpio: GPIO12
  rel2_gpio: GPIO5
  rel3_gpio: GPIO4
  rel4_gpio: GPIO15
  key1_gpio: GPIO0
  key2_gpio: GPIO9
  key3_gpio: GPIO10
  key4_gpio: GPIO14
  rx_gpio: GPIO3
  tx_gpio: GPIO1

  valve_switch_1_name: Backyard - Terraza
  valve_switch_2_name: Backyard - Jardinera Fondo
  valve_switch_3_name: Backyard - Pasto Shine
  valve_switch_4_name: Backyard - Pasto Shade


  devicename: sonoff-irrigation-a
  formated_name: Sonoff Irrigation A
  ip_address: 10.0.2.103
  comment: |-
    Irrigation controller A.
    Mounted on the green garden backyarn and controlling front yard plus the green garden.

    Location: Green Garden Backyard
    Device: Sonoff 4ch R3

<<: !include common/esphome/esp01_1m_irrigation.yaml

<<: !include common/common.yaml

<<: !include packages/irrigation/base.yaml

sprinkler:
  - id: backyard
    main_switch: Backyard Run-all
    auto_advance_switch: Backyard Auto Cycle Enabled
    valves:
      - valve_switch: $valve_switch_1_name Run
        valve_switch_id: relay1
        enable_switch: $valve_switch_1_name Cycle Enabled
        run_duration_number:
          name: $valve_switch_1_name Duration
          initial_value: 7
          unit_of_measurement: min
      - valve_switch: $valve_switch_2_name Run
        valve_switch_id: relay2
        enable_switch: $valve_switch_2_name Cycle Enabled
        run_duration_number:
          name: $valve_switch_2_name Duration
          initial_value: 10
          unit_of_measurement: min
      - valve_switch: $valve_switch_3_name Run
        valve_switch_id: relay3
        enable_switch: $valve_switch_3_name Cycle Enabled
        run_duration_number:
          name: $valve_switch_3_name Duration
          initial_value: 10
          unit_of_measurement: min
      - valve_switch: $valve_switch_4_name Run
        valve_switch_id: relay4
        enable_switch: $valve_switch_4_name Cycle Enabled
        run_duration_number:
          name: $valve_switch_4_name Duration
          initial_value: 2
          unit_of_measurement: min

sensor:
  # Reports how long the device has been powered (in hours) since last reboot
  - platform: uptime
    name: ${formated_name} Uptime
    update_interval: 60s
    filters:
      - lambda: return x / 3600;
    unit_of_measurement: "h"
  - platform: wifi_signal
    name: "${formated_name} Wifi Signal"
    update_interval: 60s

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/Santiago

  - platform: sntp
    id: sntp_time
    timezone: America/Santiago
    on_time_sync:
      then:
        - logger.log:
            level: INFO
            format:  "Time synchronized"
    on_time:
      # Every morning on weekdays
      - seconds: 0
        minutes: 00
        hours: 22
        then:
          - sprinkler.start_full_cycle: backyard

# number:
#   - id: backyard_start_time
#     platform: template
#     name: "Backyard Start Time"
#     mode: box
#     lambda: 'return id(sntp_time);'

# number:
#   - platform: template
#     id: backyard_ctrlr_multiplier
#     name: "Backyard Sprinkler Controller Multiplier"
#     min_value: 0.1
#     max_value: 10.0
#     step: 0.1
#     lambda: "return id(backyard).multiplier();"
#     set_action:
#       - sprinkler.set_multiplier:
#           id: backyard
#           multiplier: !lambda 'return x;'

# text_sensor:
#   - platform: homeassistant
#     name: "Start Timer"
#     id: backyard_start_time_helper
#     entity_id: input_datetime.start_irrigation
#     on_value:
#       then:
#         - lambda: |-
#             ESP_LOGD("main", "Old stored value  %i", id(my_global_int_hour));
#             ESP_LOGD("main", "The helper time is  %s", x.c_str());
#             id(my_global_int_hour) = id(my_global_int_hour) + 1;

# globals:
#    - id: my_global_int_hour
#      type: int
#      restore_value: yes
#      initial_value: '19'
