substitutions:
  led_gpio: GPIO13
  rel1_gpio: GPIO12
  rel2_gpio: GPIO5
  rel3_gpio: GPIO4
  rel4_gpio: GPIO15
  key1_gpio: GPIO0
  key2_gpio: GPIO9
  key3_gpio: GPIO10
  key4_gpio: GPIO14
  rx_gpio: GPIO3
  tx_gpio: GPIO1

  devicename: sonoff-irrigation-b
  controllername: sprinkler_controller
  formated_name: Sprinkler B
  ip_address: 10.0.2.160
  comment: |-
    Irrigation controller B.
    Frontyard

    Location: Green Garden Backyard
    Device: Sonoff 4ch R3

  valve_switch_1_name: ${formated_name}5 - Greengarden
  valve_switch_2_name: ${formated_name}6 - Jardineras Estacionamiento
  valve_switch_3_name: ${formated_name}7 - Jardin Entrada - Goteo
  valve_switch_4_name: ${formated_name}8 - Pasto Antejardin

  sensor_update_frequency: 1s

<<: !include common/esphome/esp01_1m_irrigation.yaml

<<: !include common/common.yaml

<<: !include packages/irrigation/base.yaml

sprinkler:
  - id: $controllername
    main_switch: ${formated_name} - Run Now All
    auto_advance_switch:
      name: ${formated_name} - Auto Enabled
      restore_mode: RESTORE_DEFAULT_ON
    standby_switch:
      name: ${formated_name} - Standby
    multiplier_number:
      name: "${formated_name} - Multiplier"
      initial_value: 1
      unit_of_measurement: times
      min_value: 0.1
      max_value: 5
    valves:
      - valve_switch: $valve_switch_1_name - Run All
        valve_switch_id: relay1
        enable_switch:
          name: $valve_switch_1_name - Auto
          restore_mode: RESTORE_DEFAULT_ON
        run_duration_number:
          name: $valve_switch_1_name - Duration
          initial_value: 2
          unit_of_measurement: min
      - valve_switch: $valve_switch_2_name - Run All
        valve_switch_id: relay2
        enable_switch:
          name: $valve_switch_2_name - Auto
          restore_mode: RESTORE_DEFAULT_ON
        run_duration_number:
          name: $valve_switch_2_name - Duration
          initial_value: 10
          unit_of_measurement: min
      - valve_switch: $valve_switch_3_name - Run All
        valve_switch_id: relay3
        enable_switch:
          name: $valve_switch_3_name - Auto
          restore_mode: RESTORE_DEFAULT_ON
        run_duration_number:
          name: $valve_switch_3_name - Duration
          initial_value: 10
          unit_of_measurement: min
      - valve_switch: $valve_switch_4_name - Run All
        valve_switch_id: relay4
        enable_switch:
          name: $valve_switch_4_name - Auto
          restore_mode: RESTORE_DEFAULT_ON
        run_duration_number:
          name: $valve_switch_4_name - Duration
          initial_value: 6
          unit_of_measurement: min

sensor:
  # Reports how long the device has been powered (in hours) since last reboot
  - platform: uptime
    name: ${formated_name} - Uptime
  - platform: wifi_signal
    name: "${formated_name} - Wifi Signal"

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/Santiago

  - platform: sntp
    id: sntp_time
    timezone: America/Santiago
    on_time_sync:
      then:
        - logger.log:
            level: INFO
            format:  "Time synchronized"
    on_time:
      # Every morning on weekdays
      - seconds: 0
        minutes: 00
        hours: 21
        then:
          - sprinkler.start_full_cycle: $controllername
      # Every morning on weekdays
      # - seconds: 0
      #   minutes: 00
      #   hours: 20
      #   then:
      #     - sprinkler.start_full_cycle: greengarden

# sensor:
#   - platform: template
#     name: "Active Valve Time Remaining"
#     lambda: |-
#       return id(controller).time_remaining();
#     update_interval: 1s
#   - platform: template
#     name: "Active Valve Time Remaining 2"
#     lambda: |-
#       return id(controller).valve_run_duration(1);
#     update_interval: 10s

# text_sensor:
#   - platform: template
#     id: active_valve_name
#     name: "Active Valve"

# globals:
#    - id: my_global_int_hour
#      type: int
#      restore_value: yes
#      initial_value: '19'
