---
esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m
  comment: ${comment}
  includes: ./packages/irrigation/irrigation.h
  # esp8266_restore_from_flash: true
  # on_boot:
  #   - priority: 800
  #     # ...
  #     then:
  #       - lambda: |-
  #           ESP_LOGD("main", "Old stored 800 value  %i", id(my_global_int_hour));
  #   - priority: 200
  #     # ...
  #     then:
  #       - lambda: |-
  #           ESP_LOGD("main", "Old stored 200 value  %i", id(my_global_int_hour));