---
esphome:
  name: ${devicename}
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32dev
  flash_size: 4MB
  framework:
    type: esp-idf
    version: recommended

preferences:
  flash_write_interval: 5min